-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE pagetriage_tags (
  ptrt_tag_id SERIAL NOT NULL,
  ptrt_tag_name TEXT NOT NULL,
  ptrt_tag_desc TEXT NOT NULL,
  PRIMARY KEY(ptrt_tag_id)
);

CREATE UNIQUE INDEX ptrt_tag_id ON pagetriage_tags (ptrt_tag_name);


CREATE TABLE pagetriage_page_tags (
  ptrpt_page_id INT NOT NULL,
  ptrpt_tag_id INT NOT NULL,
  ptrpt_value TEXT NOT NULL,
  PRIMARY KEY(ptrpt_page_id, ptrpt_tag_id)
);

CREATE INDEX ptrpt_tag_id_value ON pagetriage_page_tags (ptrpt_tag_id, ptrpt_value);


CREATE TABLE pagetriage_page (
  ptrp_page_id INT NOT NULL,
  ptrp_reviewed SMALLINT DEFAULT 0 NOT NULL,
  ptrp_deleted SMALLINT DEFAULT 0 NOT NULL,
  ptrp_created TIMESTAMPTZ NOT NULL,
  ptrp_tags_updated TIMESTAMPTZ NOT NULL,
  ptrp_reviewed_updated TIMESTAMPTZ NOT NULL,
  ptrp_last_reviewed_by INT DEFAULT 0 NOT NULL,
  PRIMARY KEY(ptrp_page_id)
);

CREATE INDEX ptrp_reviewed_created_page_del ON pagetriage_page (
  ptrp_reviewed, ptrp_created, ptrp_page_id,
  ptrp_deleted
);

CREATE INDEX ptrp_created_page_del ON pagetriage_page (
  ptrp_created, ptrp_page_id, ptrp_deleted
);

CREATE INDEX ptrp_del_created_page_reviewed ON pagetriage_page (
  ptrp_deleted, ptrp_created, ptrp_page_id,
  ptrp_reviewed
);

CREATE INDEX ptrp_updated_page_reviewed ON pagetriage_page (
  ptrp_tags_updated, ptrp_page_id,
  ptrp_reviewed
);

CREATE INDEX ptrp_reviewed_updated ON pagetriage_page (ptrp_reviewed_updated);
