-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/PageTriage/sql/patch_ptrp_tags_updated_nullable.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__pagetriage_page AS
SELECT  ptrp_page_id,  ptrp_reviewed,  ptrp_deleted,  ptrp_created,  ptrp_tags_updated,  ptrp_reviewed_updated,  ptrp_last_reviewed_by
FROM  /*_*/pagetriage_page;
DROP  TABLE  /*_*/pagetriage_page;
CREATE TABLE  /*_*/pagetriage_page (    ptrp_page_id INTEGER UNSIGNED NOT NULL,    ptrp_reviewed SMALLINT UNSIGNED DEFAULT 0 NOT NULL,    ptrp_deleted SMALLINT UNSIGNED DEFAULT 0 NOT NULL,    ptrp_created BLOB NOT NULL,    ptrp_tags_updated BLOB DEFAULT NULL,    ptrp_reviewed_updated BLOB NOT NULL,    ptrp_last_reviewed_by INTEGER UNSIGNED DEFAULT 0 NOT NULL,    PRIMARY KEY(ptrp_page_id)  );
INSERT INTO  /*_*/pagetriage_page (    ptrp_page_id, ptrp_reviewed, ptrp_deleted,    ptrp_created, ptrp_tags_updated,    ptrp_reviewed_updated, ptrp_last_reviewed_by  )
SELECT  ptrp_page_id,  ptrp_reviewed,  ptrp_deleted,  ptrp_created,  ptrp_tags_updated,  ptrp_reviewed_updated,  ptrp_last_reviewed_by
FROM  /*_*/__temp__pagetriage_page;
DROP  TABLE /*_*/__temp__pagetriage_page;
CREATE INDEX ptrp_reviewed_created_page_del ON  /*_*/pagetriage_page (    ptrp_reviewed, ptrp_created, ptrp_page_id,    ptrp_deleted  );
CREATE INDEX ptrp_created_page_del ON  /*_*/pagetriage_page (    ptrp_created, ptrp_page_id, ptrp_deleted  );
CREATE INDEX ptrp_del_created_page_reviewed ON  /*_*/pagetriage_page (    ptrp_deleted, ptrp_created, ptrp_page_id,    ptrp_reviewed  );
CREATE INDEX ptrp_updated_page_reviewed ON  /*_*/pagetriage_page (    ptrp_tags_updated, ptrp_page_id,    ptrp_reviewed  );
CREATE INDEX ptrp_reviewed_updated ON  /*_*/pagetriage_page (ptrp_reviewed_updated);