-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/pagetriage_tags (
  ptrt_tag_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ptrt_tag_name BLOB NOT NULL, ptrt_tag_desc BLOB NOT NULL
);

CREATE UNIQUE INDEX ptrt_tag_id ON /*_*/pagetriage_tags (ptrt_tag_name);


CREATE TABLE /*_*/pagetriage_page_tags (
  ptrpt_page_id INTEGER UNSIGNED NOT NULL,
  ptrpt_tag_id INTEGER UNSIGNED NOT NULL,
  ptrpt_value BLOB NOT NULL,
  PRIMARY KEY(ptrpt_page_id, ptrpt_tag_id)
);

CREATE INDEX ptrpt_tag_id_value ON /*_*/pagetriage_page_tags (ptrpt_tag_id, ptrpt_value);


CREATE TABLE /*_*/pagetriage_page (
  ptrp_page_id INTEGER UNSIGNED NOT NULL,
  ptrp_reviewed SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  ptrp_deleted SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  ptrp_created BLOB NOT NULL,
  ptrp_tags_updated BLOB NOT NULL,
  ptrp_reviewed_updated BLOB NOT NULL,
  ptrp_last_reviewed_by INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  PRIMARY KEY(ptrp_page_id)
);

CREATE INDEX ptrp_reviewed_created_page_del ON /*_*/pagetriage_page (
  ptrp_reviewed, ptrp_created, ptrp_page_id,
  ptrp_deleted
);

CREATE INDEX ptrp_created_page_del ON /*_*/pagetriage_page (
  ptrp_created, ptrp_page_id, ptrp_deleted
);

CREATE INDEX ptrp_del_created_page_reviewed ON /*_*/pagetriage_page (
  ptrp_deleted, ptrp_created, ptrp_page_id,
  ptrp_reviewed
);

CREATE INDEX ptrp_updated_page_reviewed ON /*_*/pagetriage_page (
  ptrp_tags_updated, ptrp_page_id,
  ptrp_reviewed
);

CREATE INDEX ptrp_reviewed_updated ON /*_*/pagetriage_page (ptrp_reviewed_updated);


CREATE TABLE /*_*/pagetriage_log (
  ptrl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ptrl_page_id INTEGER UNSIGNED NOT NULL,
  ptrl_user_id INTEGER UNSIGNED NOT NULL,
  ptrl_reviewed SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  ptrl_timestamp BLOB NOT NULL
);

CREATE INDEX ptrl_page_id_timestamp ON /*_*/pagetriage_log (ptrl_page_id, ptrl_timestamp);

CREATE INDEX ptrl_timestamp ON /*_*/pagetriage_log (ptrl_timestamp);
